# name: Create ECR Repositories

# on:
#   push:
#     branches:
#       - master
# jobs:
#   configure-Json-file:
#     runs-on: ubuntu-latest
#     outputs:
#       matrix: ${{ steps.set-matrix.outputs.matrix }}
#     steps:
#      - name: Checkout to repository
#        uses: actions/checkout@v3
#      - name: Set matrix data
#        id: set-matrix
#        run: echo "matrix=$(jq -c . < ./ecr-repo.json)" >> $GITHUB_OUTPUT
       
#   create-ecr-repo:
#     runs-on: ubuntu-latest
#     needs: configure
#     strategy:
#       matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v4
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: ${{ secrets.AWS_ROLE}}
#           aws-region: ${{ env.AWS_REGION }}
#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2
#       - name: Create ECR Repositories and Apply Lifecycle Policy
#         # run: echo ${{ matrix.repositories }}
#         uses: int128/create-ecr-repository-action@v1
#         with:
#           repository: ${{ matrix.repositories }}
#           lifecycle-policy: config/lifecycle-policy.json







