name: Pr Title Check

on:
  pull_request:
    types: [opened,edited,synchronize,reopened]

jobs:
  publish-image:
    name: Validate Pr title for Conventional Style Commit
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
    steps:
      - name: Check Pr title
        uses: amannn/action-semantic-pull-request@v5
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Pr title for ticket Number
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: /.*(\[MYI-(\d+)\]$)/
          helpMessage: "Title must contain ticket number [MYI-2]"



