# name: "Lint PR"

# on:
#   pull_request_target:
#     types:
#       - opened
#       - edited
#       - synchronize

# permissions:
#   pull-requests: read

# jobs:
#   main:
#     name: Validate PR title
#     runs-on: ubuntu-latest
#     steps:
#       - uses: amannn/action-semantic-pull-request@v5
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   


name: Pr Title Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  publish-image:
    name: Validate Pr title for Conventional Style Commit
    runs-on: myigus-ubuntu-latest

    permissions:
      pull-requests: read
    steps:
      - name: Check Pr title
        uses: amannn/action-semantic-pull-request@v5
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Check Pr title for ticket Number
      #   uses: Slashgear/action-check-pr-title@v4.3.0
      #   with:
      #     regexp: /\[MYI-.+]\s*$/
      #     helpMessage: "Title must contain ticket number [MYI-2]"



