name: Create ECR Repositories

on:
  push:
    branches:
      - master

jobs:
  create-repos:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo_name: ${{fromJson(file('repo.json')).repositories}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Set up AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: <your-region> # Replace with your AWS region

      - name: Create and Configure ECR Repositories
        run: |
           echo "Creating and configuring ECR repositories: ${{ matrix.repo_name }}"
