name: Create ECR Repositories

on:
  push:
    branches:
      - master

# jobs:
#   create-repos:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         repo_name: ["repo1", "repo2", "repo3"]

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
#       - name: Create and Configure ECR Repositories
#         run: |
#            echo "Creating and configuring ECR repositories: ${{ matrix.repo_name }}"

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v3
     - name: Set matrix data
       id: set-matrix
       run: echo "matrix=$(jq -c . < ./repo.json)" >> $GITHUB_OUTPUT

  print:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
     - run: echo ${{ matrix.name }}
