# name: Create ECR Repositories

# on:
#   push:
#     branches:
#       - master
# jobs:
#   configure:
#     runs-on: ubuntu-latest
#     outputs:
#       matrix: ${{ steps.set-matrix.outputs.matrix }}
#     steps:
#      - name: Checkout to repository
#        uses: actions/checkout@v3
#      - name: Set matrix data
#        id: set-matrix
#        run: echo "matrix=$(jq -c . < ./repo.json)" >> $GITHUB_OUTPUT

#   print:
#     runs-on: ubuntu-latest
#     needs: configure
#     strategy:
#       matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
#     steps:
#      - run: echo ${{ matrix.repositories }}


name: Create ECR Repositories

on:
  push:
    branches:
      - master

jobs:
  create-repositories:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Set matrix data
        id: set-matrix
        run: echo "::set-output name=matrix::$(cat ./repo.json | jq -c '.')"
      - name: Print repository names
        run: echo ${{fromJson(needs.create-repositories.outputs.matrix).repositories}}

