name: Read JSON Example

on:
  push:
    branches:
      - master

jobs:
  read-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read JSON File
        id: read-json
        run: |
          JSON_DATA=$(jq '.' repo.json)
          echo "::set-output name=jsonData::$JSON_DATA"

      - name: Use JSON Data
        run: |
          echo "JSON Data: ${{ steps.read-json.outputs.jsonData }}"
          REPOSITORIES=$(echo ${{ steps.read-json.outputs.jsonData }} | jq -r '.repositories[]')
          echo "Repositories: $REPOSITORIES"
