name: Create ECR Repositories

on:
  push:
    branches:
      - master
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v4
     - name: Set matrix data
       id: set-matrix
       run: echo "matrix=$(jq -c . < ./repo.json)" >> $GITHUB_OUTPUT
     - name: Output Repository name
       id: repos
       run: echo ${{ fromJson(steps.set-matrix.outputs.matrix) }}
     - name: Out repository
       run: echo ${{ steps.repos.outputs}}

    #  "${{ steps.set-matrix.outputs.matrix}}"
       
  # print:
  #   runs-on: ubuntu-latest
  #   needs: configure
  #   strategy:
  #     matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
  #   steps:
  #    - run: echo ${{ matrix.repositories }}




